//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicio
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Servicio.SerivicioIncialSoap")]
    public interface SerivicioIncialSoap
    {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HolaMundoResult del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HolaMundo", ReplyAction="*")]
        Servicio.HolaMundoResponse HolaMundo(Servicio.HolaMundoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HolaMundo", ReplyAction="*")]
        System.Threading.Tasks.Task<Servicio.HolaMundoResponse> HolaMundoAsync(Servicio.HolaMundoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HolaMundoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HolaMundo", Namespace="http://tempuri.org/", Order=0)]
        public Servicio.HolaMundoRequestBody Body;
        
        public HolaMundoRequest()
        {
        }
        
        public HolaMundoRequest(Servicio.HolaMundoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HolaMundoRequestBody
    {
        
        public HolaMundoRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HolaMundoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HolaMundoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Servicio.HolaMundoResponseBody Body;
        
        public HolaMundoResponse()
        {
        }
        
        public HolaMundoResponse(Servicio.HolaMundoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HolaMundoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HolaMundoResult;
        
        public HolaMundoResponseBody()
        {
        }
        
        public HolaMundoResponseBody(string HolaMundoResult)
        {
            this.HolaMundoResult = HolaMundoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface SerivicioIncialSoapChannel : Servicio.SerivicioIncialSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class SerivicioIncialSoapClient : System.ServiceModel.ClientBase<Servicio.SerivicioIncialSoap>, Servicio.SerivicioIncialSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SerivicioIncialSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(SerivicioIncialSoapClient.GetBindingForEndpoint(endpointConfiguration), SerivicioIncialSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SerivicioIncialSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SerivicioIncialSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SerivicioIncialSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SerivicioIncialSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SerivicioIncialSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Servicio.HolaMundoResponse Servicio.SerivicioIncialSoap.HolaMundo(Servicio.HolaMundoRequest request)
        {
            return base.Channel.HolaMundo(request);
        }
        
        public string HolaMundo()
        {
            Servicio.HolaMundoRequest inValue = new Servicio.HolaMundoRequest();
            inValue.Body = new Servicio.HolaMundoRequestBody();
            Servicio.HolaMundoResponse retVal = ((Servicio.SerivicioIncialSoap)(this)).HolaMundo(inValue);
            return retVal.Body.HolaMundoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Servicio.HolaMundoResponse> Servicio.SerivicioIncialSoap.HolaMundoAsync(Servicio.HolaMundoRequest request)
        {
            return base.Channel.HolaMundoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Servicio.HolaMundoResponse> HolaMundoAsync()
        {
            Servicio.HolaMundoRequest inValue = new Servicio.HolaMundoRequest();
            inValue.Body = new Servicio.HolaMundoRequestBody();
            return ((Servicio.SerivicioIncialSoap)(this)).HolaMundoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SerivicioIncialSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.SerivicioIncialSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SerivicioIncialSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:63803/SerivicioIncial.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.SerivicioIncialSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:63803/SerivicioIncial.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            SerivicioIncialSoap,
            
            SerivicioIncialSoap12,
        }
    }
}
